<?php
    include _include(ADMIN_PATH.'view/htm/header.inc.htm');
    $config = getConfig()
?>
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">CloudFlare Turnstile 设置</h3>
        </div>
        <div class="card-body">
            <p class="card-text"><del>应该没啥逼用()</del></p>
            <div class="alert alert-success msg" style="display: none"></div>
            <form>
                <div class="form-group">
                    <label for="<?php echo siteKey ?>">Site Key : </label>
                    <input placeholder="请输入您的Site Key" type="text" id="<?php echo siteKey ?>" name="<?php echo siteKey ?>" value="<?php echo $config[siteKey]  ?>" >
                    <small class="form-text text-muted">https://developers.cloudflare.com/turnstile/get-started/#new-sites</small>
                </div>
                <div class="form-group">
                    <label for="<?php echo secretKey ?>">Secret Key : </label>
                    <input placeholder="请输入您的Secret Key" type="text" id="<?php echo secretKey ?>" name="<?php echo secretKey ?>" value="<?php echo $config[secretKey]  ?>" >
                </div>
                <button type="button" id="submit" class="btn btn-primary">确定</button>
            </form>
        </div>
    </div>
</div>
<script src="/view/js/jquery-3.1.0.js<?php echo $static_version;?>"></script>
<script>
    let timer = null;
    $("#submit").click(()=>{
        $.post(null,$('form').serialize(),r=>{
            $(".msg").text((r&&r.code === 1) ? "修改成功" : JSON.stringify(r)).show();
        },'json');
        if (!timer) clearTimeout(timer)
        timer = setTimeout(()=>{$(".msg").hide()},1500)
    })
</script>